// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type bpfBss struct{ PktCount uint64 }

// LoadPktCount interacts with the provided map to load the value of the pkt_count variable.
// The Bss map for which the bpfBss structure has been generated must be provided,
// otherwise an error will be returned.
func (b *bpfBss) LoadPktCount(m *ebpf.Map) error {
	if m.Name() != ".bss" {
		return fmt.Errorf("wrong map provided to LoadPktCount: expected .bss, got %s", m.Name())
	}
	return m.LoadAt(0, uint32(0), &b.PktCount)
}

// StorePktCount interacts with the provided map to store the value of the pkt_count variable.
// The Bss map for which the bpfBss structure has been generated must be provided,
// otherwise an error will be returned.
func (b *bpfBss) StorePktCount(m *ebpf.Map) error {
	if m.Name() != ".bss" {
		return fmt.Errorf("wrong map provided to StorePktCount: expected .bss, got %s", m.Name())
	}
	return m.StoreAt(0, uint32(0), &b.PktCount)
}

type bpfData struct {
	Random uint32
	VarMsg [16]int8
}

// LoadRandom interacts with the provided map to load the value of the random variable.
// The Data map for which the bpfData structure has been generated must be provided,
// otherwise an error will be returned.
func (b *bpfData) LoadRandom(m *ebpf.Map) error {
	if m.Name() != ".data" {
		return fmt.Errorf("wrong map provided to LoadRandom: expected .data, got %s", m.Name())
	}
	return m.LoadAt(0, uint32(0), &b.Random)
}

// StoreRandom interacts with the provided map to store the value of the random variable.
// The Data map for which the bpfData structure has been generated must be provided,
// otherwise an error will be returned.
func (b *bpfData) StoreRandom(m *ebpf.Map) error {
	if m.Name() != ".data" {
		return fmt.Errorf("wrong map provided to StoreRandom: expected .data, got %s", m.Name())
	}
	return m.StoreAt(0, uint32(0), &b.Random)
}

// LoadVarMsg interacts with the provided map to load the value of the var_msg variable.
// The Data map for which the bpfData structure has been generated must be provided,
// otherwise an error will be returned.
func (b *bpfData) LoadVarMsg(m *ebpf.Map) error {
	if m.Name() != ".data" {
		return fmt.Errorf("wrong map provided to LoadVarMsg: expected .data, got %s", m.Name())
	}
	return m.LoadAt(4, uint32(0), &b.VarMsg)
}

// StoreVarMsg interacts with the provided map to store the value of the var_msg variable.
// The Data map for which the bpfData structure has been generated must be provided,
// otherwise an error will be returned.
func (b *bpfData) StoreVarMsg(m *ebpf.Map) error {
	if m.Name() != ".data" {
		return fmt.Errorf("wrong map provided to StoreVarMsg: expected .data, got %s", m.Name())
	}
	return m.StoreAt(4, uint32(0), &b.VarMsg)
}

type bpfRodata struct {
	ConstMsg [16]int8
	_        [72]byte
}

// LoadConstMsg interacts with the provided map to load the value of the const_msg variable.
// The Rodata map for which the bpfRodata structure has been generated must be provided,
// otherwise an error will be returned.
func (b *bpfRodata) LoadConstMsg(m *ebpf.Map) error {
	if m.Name() != ".rodata" {
		return fmt.Errorf("wrong map provided to LoadConstMsg: expected .rodata, got %s", m.Name())
	}
	return m.LoadAt(0, uint32(0), &b.ConstMsg)
}

// StoreConstMsg interacts with the provided map to store the value of the const_msg variable.
// The Rodata map for which the bpfRodata structure has been generated must be provided,
// otherwise an error will be returned.
func (b *bpfRodata) StoreConstMsg(m *ebpf.Map) error {
	if m.Name() != ".rodata" {
		return fmt.Errorf("wrong map provided to StoreConstMsg: expected .rodata, got %s", m.Name())
	}
	return m.StoreAt(0, uint32(0), &b.ConstMsg)
}

type bpfRodatanamed struct{ ConstNamedMsg [26]int8 }

// LoadConstNamedMsg interacts with the provided map to load the value of the const_named_msg variable.
// The Rodatanamed map for which the bpfRodatanamed structure has been generated must be provided,
// otherwise an error will be returned.
func (b *bpfRodatanamed) LoadConstNamedMsg(m *ebpf.Map) error {
	if m.Name() != ".rodata.named" {
		return fmt.Errorf("wrong map provided to LoadConstNamedMsg: expected .rodata.named, got %s", m.Name())
	}
	return m.LoadAt(0, uint32(0), &b.ConstNamedMsg)
}

// StoreConstNamedMsg interacts with the provided map to store the value of the const_named_msg variable.
// The Rodatanamed map for which the bpfRodatanamed structure has been generated must be provided,
// otherwise an error will be returned.
func (b *bpfRodatanamed) StoreConstNamedMsg(m *ebpf.Map) error {
	if m.Name() != ".rodata.named" {
		return fmt.Errorf("wrong map provided to StoreConstNamedMsg: expected .rodata.named, got %s", m.Name())
	}
	return m.StoreAt(0, uint32(0), &b.ConstNamedMsg)
}

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
}

// bpfSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	XdpProgFunc *ebpf.ProgramSpec `ebpf:"xdp_prog_func"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	Bss         *ebpf.MapSpec `ebpf:".bss"`
	Data        *ebpf.MapSpec `ebpf:".data"`
	Rodata      *ebpf.MapSpec `ebpf:".rodata"`
	Rodatanamed *ebpf.MapSpec `ebpf:".rodata.named"`
	MapPktCount *ebpf.MapSpec `ebpf:"map_pkt_count"`
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	Bss         *ebpf.Map `ebpf:".bss"`
	Data        *ebpf.Map `ebpf:".data"`
	Rodata      *ebpf.Map `ebpf:".rodata"`
	Rodatanamed *ebpf.Map `ebpf:".rodata.named"`
	MapPktCount *ebpf.Map `ebpf:"map_pkt_count"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.Bss,
		m.Data,
		m.Rodata,
		m.Rodatanamed,
		m.MapPktCount,
	)
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	XdpProgFunc *ebpf.Program `ebpf:"xdp_prog_func"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.XdpProgFunc,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfeb.o
var _BpfBytes []byte
